### ISSUE TITLE
Test for autoincrement in database_test might be wrong

### ISSUE THREAD

**Issue by mweibel** [meh/amnesia#23]
The defined table `User` is defined as an `ordered_set`. According to [the OTP source code](https://github.com/erlang/otp/blob/maint/lib/mnesia/src/mnesia.erl#L1606), `:mnesia.dirty_update_counter` does only work on tables/records defined as `set`. 

Is this assumption correct?

**Comment by ulrikaugustsson** [comment]
@mweibel do you remember how you solved this? Getting the same error and I'm a bit too new to elixir to figure this out.

**Comment by mweibel** [comment]
@ulrikaugustsson hmm, checking my commit from then.. don't recall exactly what solved the issue, but there are some hints which might help you:
I use an own mix task to create the database tables which used to (previously to my fix probably related to this issue) try to create each table on its own instead of creating the database and then fixing the copying afterwards, i.e.

before:
```
Database.User.create 
Database.UserStatus.create disk: [node]
#.... more
```

after:
```
Database.create
Database.UserStatus.copying(node, :disk)
```

does that fix the issue? if not, I have some other changes in the same commit, but not sure if they're related or not... ;)

**Comment by ulrikaugustsson** [comment]
Thanks for the answer, I think I got it working some how, I did a commit after I got it working so might be able to find what I did there if any one else has this problem.
