### ISSUE TITLE
Hangs on the Database.wait in "install" mix task

### ISSUE THREAD

**Issue by alg** [meh/amnesia#31]
Hey there,

Thanks for the wrapper. I'm having trouble following samples. I defined the Database module, then Install / Uninstall tasks and after compiling and running "iex -S mix install" I can see that it hangs on the Database.wait line infinitely.

Any ideas what to try or where to look for help are greatly appreciated!

**Comment by jangromko** [comment]
@alg I'm having the same issue here, what that error actually means?

**Comment by alg** [comment]
@jangromko can't recall, mate. Tons of water down the bridge. I'll ping you if I do.
