### ISSUE TITLE
Warnings with latest and Elixir 1.1.1

### ISSUE THREAD

**Issue by cjimison** [meh/amnesia#41]
Just upgraded to elixir 1.1.1 did a mix deps.update amnesia and now I am seeing the following warning

==> exquisite
warning: the dependency :exquisite requires Elixir "~> 1.0.0-rc1" but you are running on v1.1.1

Everything is working, just though I would report this.

**Comment by meh** [comment]
What version are you using?

**Comment by cjimison** [comment]
elixir 1.1.1

From mix.lock file:

"amnesia": {:git, "https://github.com/meh/amnesia.git", "d0524ae81e07eb94d56e8a34540420b13178df09", [branch: "master"]}, 

Just did the mix deps.update amnesia like 20 min. ago

 "exquisite": {:hex, :exquisite, "0.1.4"},

**Comment by meh** [comment]
Ah exquisite, derp, I thought the warning was for amnesia :panda_face:

**Comment by meh** [comment]
Ok, published a new version of exquisite with the requirement updated, thanks for the heads up.
