### ISSUE TITLE
delete() not working on a table

### ISSUE THREAD

**Issue by squaregear** [meh/amnesia#43]
When I do MyTableName.delete(MyTableName, "mykey") I get "** (CaseClauseError) no case clause matching: "mykey"". Am I passing the name parameter wrong? The documentation basically just says, "see mnesia:delete". The mnesia:delete documentation says to pass the name of the table, but that seems unnecessary, since I've already specified the table with MyTableName.delete(). I like your library (and it's license terms) and I'd like to use it, but I'm really stuck here.

**Comment by meh** [comment]
There are two functions to delete an item from a table.

`Amnesia.Table.delete` which takes the table name and the key.

And `<Table>.delete` which just takes the key (or struct).

**Comment by squaregear** [comment]
Well that was a deflatingly obvious solution. Thanks for the help and sorry for my Monday-brain.
