### ISSUE TITLE
How to create the database on production machine without mix

### ISSUE THREAD

**Issue by twinfire** [meh/amnesia#45]
I am using exrm to create my uat and production releases.  They are created with all the compiled beams as well as the erts and tar'd and zipped into a standalone file that gets extracted on the target box.  How am I supposed to create the initial mnesia db via amnesia (mix amnesia.create -db Database) on the target box?  

Thanks 

Geoff

**Comment by twinfire** [comment]
Nevermind, I just mimicked what the mix task was doing.

**Comment by skovsgaard** [comment]
Just out of curiosity, will mimicking what the mix task is doing work just as well if run as a standalone .exs script?
