### ISSUE TITLE
License update

### ISSUE THREAD

**Issue by TreyE** [meh/amnesia#52]
Is there any chance you would be considering changing the chosen license?

I work in a start up where we are adopting Elixir and would love to use this package, but I see two major problems:

1. Your license terms basically allow me to wholesale steal your code without giving you credit.  Obviously I don't want to do this because it's not just a jerk move, I consider it bad open source form to not give credit to the guy who did all the heavy lifting.
2. We integrate with enterprise customers, and as much as I love the ideals behind the license, there's no way I can convince to my boss or our clients to adopt software filled with a bunch of f-bombs, no matter how awesome.  As stupid a thing as this is to prevent the usage of awesome software, corporate attitudes can hurt adoption.

Any idea if this could be changed to an equally permissive license which also gives you more credit while not horrifying a bunch of stuffed shirts?

**Comment by subsoap** [comment]
Fork it, give them credit, remove the f-bombs from the license?

**Comment by meh** [comment]
Nope, I'm sorry, I strongly believe in the WTFPL.

1. The intention is to put it under public domain, but that cannot be done in my country, so I use the WTFPL.
2. This is **extremely** intended, I do not want to help companies that are backwards (most of them) and reject software on the grounds of "these words in some random source code hurt my feelings", or companies that are composed of more lawyers than engineers and reject software on gray legal ground (i.e. Oracle).

Do feel free to fork it, add a `sed` hook to remove the license on pull and bundle it up with whatever, this is my way of fighting corporate retardation with an even more retarded mean which makes the whole thing insanely hilarious (to me).

I am sorry for you getting in the crossfire of this pointless war tho :rage4:

**Comment by skovsgaard** [comment]
@TreyE, you could do one of the following:

1. Fork and alter it to an equally permissive license (e.g. Unlicense) and give credit as you see fit.
2. I'm aware that this is may be defeating the purpose, but: Using Mnesia without a wrapper is still an option and like the rest of OTP, Mnesia is Apache 2 licensed.
