### ISSUE TITLE
Compiling with Elixir 1.3 give the following warnings

### ISSUE THREAD

**Issue by cjimison** [meh/amnesia#56]
warning: function Amnesia.result/1 is undefined or private
Found at 7 locations:
  lib/amnesia.ex:159
  lib/amnesia.ex:168
  lib/amnesia.ex:194
  lib/amnesia.ex:204
  lib/amnesia.ex:229
  lib/amnesia.ex:255
  lib/amnesia.ex:281

**Comment by meh** [comment]
I think it may be a bug in the checker, `Amnesia.result` is a macro, and if it really didn't work nothing would work at all.

**Comment by meh** [comment]
Or maybe not, I think all those locations are the non-macro variants for transactions, and it has the usual chicken and egg problem of using a macro in a function defined in the module where the macro is defined.

**Comment by meh** [comment]
Ok, fixed and published a new version.
