### ISSUE TITLE
Amnesia 0.2.5 / Elixir 1.4.2 defdatabase warning (x4): variable "metadata" does not exist...

### ISSUE THREAD

**Issue by adamdaugherty** [meh/amnesia#65]
Using Amnesia 0.2.5 with Elixir 1.4.2, I see a warning repeated 4 times for every line where the `defdatabase` macro is called during compilation (via `mix compile`, if that makes a difference). Luckily, it's reproducible by simply making a new `test.ex` file with the following contents:

```elixir
use Amnesia

defdatabase Test do
end
```

Compiling the above will result in the following, repeated 4 times for every use of `defdatabase` in each file being compiled:

```
warning: variable "metadata" does not exist and is being expanded to "metadata()", please use parentheses to remove the ambiguity or change the variable name
```

**Comment by meh** [comment]
Should be fixed now.

**Comment by adamdaugherty** [comment]
Hey, thanks a bunch for fixing this. Everything looks good from my end.
