### ISSUE TITLE
"Backup restore" doesn't restore the last value of "autoincrement" column

### ISSUE THREAD

**Issue by macabeus** [meh/amnesia#72]
I'm using [backup commands](https://github.com/meh/amnesia/blob/af8e4ce37ee12a4af71209720bbed1aab2891cf7/lib/amnesia/backup.ex) to create a snapshot of my database.
To create a snapshot, I'm using this code:

```
Amnesia.Backup.checkpoint(%{
  name: 'backup',
  max: [Database.Account, Database.VerifyCode],
  override: true
})
Amnesia.Backup.start('backup', 'backup')
```

It's works, creating a file called `backup`. But, when I restore this snapshot using

```
Amnesia.Backup.restore('backup', nil)
```

The tables that has an `autoincrement` column get problem, because the `restore` command doesn't restore the counter.
For example, if I restore the `Account` table, I get 5 rows from `backup` file, then, if I to add a new record on this table, the new record will replace the first record (because will have the same id, 1, instead of the correct id, 5).

**Comment by meh** [comment]
You need to backup the metadata table as well.

**Comment by macabeus** [comment]
Nice!
I fixed it using

```
Amnesia.Backup.checkpoint(%{
  name: 'backup',
  max: [Database.Account, Database.VerifyCode, Database],
  override: true
})
```

In order to prevent this problem happens again, could I to add this detail on documentation? Or maybe is better to add a function to backup whole the database, including the metadata table?

**Comment by meh** [comment]
A note in the documentation would be fine.
